### ISSUE TITLE
how can i fix 403 error?

### ISSUE THREAD

**Issue by huxuxuya** [nsdkinx/vkmax#9]
I try run example but catch error: websockets.exceptions.InvalidStatus: server rejected WebSocket connection: HTTP 403

**Comment by DarkCat09** [comment]
It was fixed in #5 but a new version hasn't been released on pypi yet, so you need to install the library from `main` git branch

**Comment by camanchaca-by** [comment]
The issue is still not fixed? I've got `'phone-auth-enabled': False ` in opcode 6 response. It appears that the web client requires QR code authentication to work.

**Comment by DarkCat09** [comment]
@camanchaca-by 
Please see #27 for auth changes info
